name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t ts-auth-service-1818 .

      - name: Save Docker image to a tar file
        run: |
          docker save ts-auth-service-1818 > ts-auth-service-1818.tar

      - name: Upload Docker image to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: docker-image
          path: ts-auth-service-1818.tar

      - name: Download Docker image on EC2
        uses: appleboy/drone-ssh@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo yum install -y docker
            sudo systemctl start docker
            mkdir -p /home/ec2-user/ts-auth-service-1818
            cd /home/ec2-user/ts-auth-service-1818
            
            # Download artifact using GitHub API
            curl -L -o ts-auth-service-1818.tar \
              -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
              "https://api.github.com/repos/${{ github.repository }}/actions/artifacts/${{ steps.upload-artifact.outputs.artifact-id }}/zip"

            # Extract and load Docker image
            docker load -i ts-auth-service-1818.tar
            docker run -d -p 3000:3000 ts-auth-service-1818
